### ISSUE TITLE
Laptop Sleeves and Cases

### ISSUE THREAD

**Issue by Morpheus636** [Morpheus636/awesome-framework#10]
Looking for some laptop sleeves and cases that people have successfully used with the Framework so I can add them to the repo. If you've used any, post it in the comments of this issue. Include a link if possible.

**Comment by MinaDarsh** [comment]
Case Logic Reflect 13", the laptop fits with a little bit of room to spare but not crazy much, careful that you don't accidently take the Macbook version as that one has a different internal measurement and won't fit around the laptop. (I tested it in stores.)

https://www.caselogic.com/en-us/laptop-bags/laptop-sleeves/case-logic-reflect-13-laptop-sleeve-_-3204690

**Comment by Khilseith** [comment]
Saw a [forum post](https://community.frame.work/t/compatible-protective-case/2429/3) where someone recommended a [FINPAC Hard Laptop Sleeve Case for MacBook Pro](https://www.amazon.com/FINPAC-Inspiron-Shockproof-Water-Resistant-Protective/dp/B088WNMW8N). So that's what I've been using, and I like it a lot!

It fits very snug!
![Case](https://user-images.githubusercontent.com/78451857/203660907-33410c53-bf21-42d3-b185-0b0027453700.jpg)

**Comment by Morpheus636** [comment]
Just a heads up, all three community validated hardware requests will be added tonight or tomorrow and these RFC issues will be closed. If anyone has others to add, please do so now.

Once they're closed, please open a new issue for anything additional you'd like to see added.
